stages:
  - build
  - deploy

variables:
  CONTAINER_IMAGE: kaiiiiii/glassfish:${CI_COMMIT_SHORT_SHA}

build:
  image: docker:latest
  services:
  - docker:dind
  stage: build
  tags:
    - docker
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} kaiiiiii/glassfish:latest
    - docker push ${CONTAINER_IMAGE}
    
deploy:
  services:
  - docker:dind
  stage: deploy
  tags:
    - cluster
    - kubernetes
  script:
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
    - kubectl apply -f deployment.yaml