apiVersion: apps/v1
kind: Deployment
metadata:
  name: testglassfish
  labels:
    app: glassfish
spec:
  replicas: 2
  selector:
    matchLabels:
      app: glassfish
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: glassfish
    spec:
      containers:
        - name: glassfish
          image: kaiiiiii/glassfish:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2